repositoryUrl: https://github.com/dynamsoft-docs/barcode-reader-docs/blob/master
repositoryUrlJS: https://github.com/dynamsoft-docs/barcode-reader-docs-js/blob/main
repositoryUrlMobile: https://github.com/dynamsoft-docs/barcode-reader-docs-mobile/blob/main
repositoryUrlServer: https://github.com/dynamsoft-docs/barcode-reader-docs-server/blob/main
repository: dynamsoft-docs/barcode-reader-docs-server
docFullPath: https://www.dynamsoft.com/barcode-reader/docs/server/
firstLevelUrl: /barcode-reader/docs/server
docHomePage: /barcode-reader/docs/core/introduction/

useVersionTree: true

features: /barcode-reader/docs/programming/features/
introduction: /barcode-reader/docs/introduction/
programming: /barcode-reader/docs/programming/
parameters: /barcode-reader/docs/parameters/
license_activation: /barcode-reader/docs/license-activation/
release_notes: /barcode-reader/docs/release-notes/
performance: /barcode-reader/docs/performance/
faq: /barcode-reader/docs/faq/

c_cplusplus: /barcode-reader/docs/server/programming/c-cplusplus/
structs: /barcode-reader/docs/server/programming/c-cplusplus/struct/

c: /barcode-reader/docs/server/programming/c/
c_api: /barcode-reader/docs/server/programming/c/api-reference/
c_methods: /barcode-reader/docs/server/programming/c/api-reference/methods/
c_release_notes: /barcode-reader/docs/server/programming/c/release-notes/

cpp: /barcode-reader/docs/server/programming/cplusplus/
cpp_api: /barcode-reader/docs/server/programming/cplusplus/api-reference/
cpp_methods: /barcode-reader/docs/server/programming/cplusplus/api-reference/cbarcodereader-methods/
cpp_release_notes: /barcode-reader/docs/server/programming/cplusplus/release-notes/

dotnet: /barcode-reader/docs/server/programming/dotnet/
dotnet_api: /barcode-reader/docs/server/programming/dotnet/api-reference/
dotnet_methods: /barcode-reader/docs/server/programming/dotnet/api-reference/BarcodeReader/
dotnet_class: /barcode-reader/docs/server/programming/dotnet/api-reference/class/
dotnet_release_notes: /barcode-reader/docs/server/programming/dotnet/release-notes/

java: /barcode-reader/docs/server/programming/java/
java_api: /barcode-reader/docs/server/programming/java/api-reference/
java_methods: /barcode-reader/docs/server/programming/java/api-reference/BarcodeReader/
java_class: /barcode-reader/docs/server/programming/java/api-reference/class/
java_release_notes: /barcode-reader/docs/server/programming/java/release-notes/

python: /barcode-reader/docs/server/programming/python/
python_api: /barcode-reader/docs/server/programming/python/api-reference/
python_methods: /barcode-reader/docs/server/programming/python/api-reference/BarcodeReader/
python_class: /barcode-reader/docs/server/programming/python/api-reference/class/
python_release_notes: /barcode-reader/docs/server/programming/python/release-notes/

assets: /barcode-reader/docs/server/assets/
edit_icon: /barcode-reader/docs/server/assets/img-icon/edit-icon.png
smile_icon: /barcode-reader/docs/server/assets/img-icon/icon-smile.png
sad_icon: /barcode-reader/docs/server/assets/img-icon/icon-sad.png
dbr_icon: /barcode-reader/docs/server/assets/img-icon/icon-dbr.svg
dwt_icon: /barcode-reader/docs/server/assets/img-icon/icon-dwt.svg
dnt_icon: /barcode-reader/docs/server/assets/img-icon/icon-dnt.svg

camera: /camera-enhancer/docs/introduction/

baseurl: "/barcode-reader/docs/server"
plugins:
  - jemoji

defaults:
  - scope:
      path: ""
    values:
      category: "original-repo"
      edition: "algorithm"
  - scope:
      path: "programming/javascript"
    values:
      category: "js-repo"
      edition: "js"
  - scope:
      path: "programming/android"
    values:
      category: "mobile-repo"
      edition: "mobile"
  - scope:
      path: "programming/objectivec-swift"
    values:
      category: "mobile-repo"
      edition: "mobile"
  - scope:
      path: "programming/c"
    values:
      category: "original-repo"
      edition: "desktop"
  - scope:
      path: "programming/cplusplus"
    values:
      category: "original-repo"
      edition: "desktop"
  - scope:
      path: "programming/c-cplusplus"
    values:
      category: "original-repo"
      edition: "desktop"
  - scope:
      path: "programming/dotnet"
    values:
      category: "original-repo"
      edition: "desktop"
  - scope:
      path: "programming/python"
    values:
      category: "original-repo"
      edition: "desktop"
  - scope:
      path: "programming/java"
    values:
      category: "original-repo"
      edition: "desktop"
  - scope:
      path: ""
    values:
      layout: "default-layout"
      noTitleIndex: true
      needAutoGenerateSidebar: true
      needGenerateH3Content: true

url: "https://www.dynamsoft.com" # sitemap root
